swimapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getinfo, name='index'),
]

swimsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('swimapp.urls')),
    path('swimapp/pool', include('swimapp.urls')),
]

swimapp/models.py
from django.db import models
from datetime import datetime

class City(models.Model):
    city_name = models.CharField(max_length = 20, default='')
    def __str__(self):
        return self.city_name

class Pool(models.Model):
    city = models.ForeignKey(City, default='', on_delete = models.CASCADE)
    pool_name = models.CharField(max_length = 30, default='')
    price = models.TextField(null=True)
    info = models.TextField(null=True)
    homepage = models.CharField(max_length=30, default='')
    note = models.TextField(default='', blank=True)

    def __str__(self):
        return self.pool_name

class Timetable(models.Model):
    pool = models.ForeignKey(Pool, on_delete = models.CASCADE)
    start_time = models.TimeField(auto_now=False, auto_now_add=False)
    end_time = models.TimeField(auto_now=False, auto_now_add=False)

    DAY_CHOICES = [
        (1, "월요일"),
        (2, "화요일"),
        (3, "수요일"),
        (4, "목요일"),
        (5, "금요일"),
        (6, "토요일"),
        (7, "일요일"),
    ]
    day = models.IntegerField(
        choices = DAY_CHOICES,
        default = 1,
    )

    def __str__(self):
        title = '{0.pool} {0.day} {0.start_time}'
        return title.format(self)

class TimeInterval(models.Model):

    TIME_CHOICES = (
        ('', ' '),
        (5, "5시간"),
        (12, "12시간"),
        (24, "24시간")
    )

swimapp/forms.py
from django import forms
from datetime import datetime, date
from .models import City, TimeInterval
from django.forms import ModelChoiceField

class CheckForm(forms.Form):
    cities = forms.ModelChoiceField(
        label='',
        required=True,
        queryset=City.objects.all(),
        empty_label='',
        widget=forms.Select(attrs={'class': 'form_select'})
        )

    times = forms.ChoiceField(
        label='',
        choices=TimeInterval.TIME_CHOICES,
        widget=forms.Select(attrs={'class': 'form_select'})
    )

    class Meta:
        model = City
        fields = ['city_name']

swimapp/views.py
from django.shortcuts import render
from .models import City, Pool, Timetable, TimeInterval
from .forms import CheckForm
from django.http import HttpResponseRedirect
from django.db.models import Q

from datetime import date, datetime, timedelta, time

def getinfo(request):
    if request.method == 'POST':
        form = CheckForm(request.POST)
        if form.is_valid():
            user_city = form.cleaned_data['cities']
            user_timeinterval = int(form.cleaned_data['times'])
            date = datetime.now()
            transfered_date = date + timedelta(hours = user_timeinterval)
            weekday = transfered_date.isoweekday()
            hour = date.hour + user_timeinterval
            pool_list = Pool.objects.filter(city=user_city)

            if hour >= 24:
                if weekday == 1:
                    time_list = Timetable.objects.filter(pool__in=pool_list, day=7, start_time__gte=date.time(), end_time__lte=time(23,59,59)) | Timetable.objects.filter(day=1, start_time__gte=time(0,0,0), end_time__lt=transfered_date.time())
                else:
                    time_list = Timetable.objects.filter(Q(pool__in=pool_list, day=weekday-1, start_time__gte=date.time(), end_time__lte=time(23,59,59)) | Q(pool__in=pool_list, day=weekday, start_time__gte=time(0,0,0), end_time__lt=transfered_date.time()))
            else:
                time_list = Timetable.objects.filter(pool__in=pool_list, day=weekday, start_time__gte=date.time(), end_time__lt=transfered_date.time())

            return render(request, 'swimapp/pool.html', {'pool_list': pool_list, 'time_list': time_list})
    else:
        form = CheckForm()
        return render(request, 'swimapp/index.html', {'form':form})

swimapp/templates/swimapp/base.html
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>SWIM, SWIM!</title>
        <link rel="stylesheet" href="{% static 'swimapp/css/style.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR&display=swap" rel="stylesheet">
        <script src="{% static 'js/note.js' %}" type="text/javascript" async></script>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

swimapp/templates/swimapp/index.html
{% extends 'swimapp/base.html' %}
{% block content %}
  <div class="logoBox">
    <div class="logo_helper"></div>
    <a href=""> <img src="../../static/swimapp/images/logo_gif_2.gif" id="logo" /></a> <br>
  </div>
    <div class="description_box">
      <div class="helper"></div>
      <div class="description">
        <div class="firstLine1">
          지금 당장&nbsp;
          <br class="breakMobile">
        </div>
          <div class="firstLine2">
            <span class="box1">자유수영</span>을 할 수 있는<br>
          </div>
        <div class="secondLine">
          <span class="box2">수영장</span>이 알고 싶다면?
        </div>
      </div>
    </div>
    <div class="background">
      <div class="infoForm">
        <form method="POST" class="form">{% csrf_token %}
          <div class="formLine">
              <div id="citi_form"> {{ form.cities }} <span class="text">에 있는 </span> </div>
              <div id="time_form"> {{ form.times }} <span class="text">내의 <br class="breakMobile">수영장으로 </span></div>
          </div>
            <button id="btn" type="submit" value="Save">찾아보자!</button>
        </form>
      </div>
      <div class="feedback">
        <a href="mailto:jeanP.tech@gmail.com" target="_blank">피드백</a>
      </div>
    </div>

{% endblock %}

swimapp/templates/swimapp/pool.html
{% extends 'swimapp/base.html' %}
{% block content %}
  <div class="logoBox2">
    <div class="logo_helper"></div>
    <a href=""> <img src="../../static/swimapp/images/logo_gif_white.gif" id="logo" /></a> <br>
  </div>
  <div class="time_list">
    {% if time_list %}
      {% for pool in pool_list %}
        <h2> {{ pool|linebreaks }} </h2>
        <div class="container">
          <div class="section1">
            <h3>이용시간</h3>
              {% for time in time_list %}
                {% if pool|stringformat:"s" == time.pool|stringformat:"s" %}
                {% ifchanged time.day %}
                  {{ time.get_day_display|linebreaks }}
                {% endifchanged %}
                  <div class="textInContainer">
                    {{ time.start_time|time:"H:i" }} ~
                    {{ time.end_time|time:"H:i" }}
                  </div>
                {% endif %}
              {% endfor %}
          </div>
          <div class="section2">
            <h3>이용가격</h3>
              <div class="textInContainer">
                {{ pool.price|linebreaks }}
              </div>
          </div>
        </div>
        <div class="noteContainer">
          <div class="note"> 자세히 </div>
            <div class="note_contents">
              <div class="info"> {{ pool.info|linebreaks }} </div>
              <div class="homepage"> {{ pool.homepage|urlize }} </div>
              <button onclick="parent.open('{{ pool.homepage }}')" type="button" class="homepageBtn">홈페이지</button>
              {% if pool.note %}
                <div class="notice">
                  {{ pool.note|linebreaks }}
                </div>
              {% endif %}
            </div>
        </div>
      {% endfor %}
    {% else %}
      <div class="no_pool">
        <div class="middle_helper"></div>
        <div class="no_pool_textBox">
          찾으시는 시간에 <br>수영장 정보가 <u>없습니다!</u>
        </div>
      </div>
    {% endif %}

  </div>
{% endblock %}